### ISSUE TITLE
Web UI inaccessable | Could not initialize NSS | Neuvector Manager pod Error

### ISSUE THREAD

**Issue by Sbennett99** [neuvector/neuvector#1704]
**Environment**
Platform: RKE2
Kubernetes/Platform Version(s):  v1.29.2+rke2r1

helm installation
chart:  2.8.3 
AppVersion: 5.4.1  

**Values**
manager.svc.type=ClusterIP (Routing using Istio) ** Have also tried a NodePort for direct access to bypass istio but the results are the same
controller.pvc.storageClass=longhorn 
controller.pvc.enabled=true 

**Error** 

Note: manager has this error when hitting the UI

```
2024-12-16 15:31:16,683|INFO |MANAGER|apache.pekko.event.slf4j.Slf4jLogger(applyOrElse:117): Slf4jLogger started
2024-12-16 15:31:20,136|INFO |MANAGER|com.neu.web.Rest$($init$$$anonfun$2:67): Server is listening on /[0:0:0:0:0:0:0:0]:8443
2024-12-16 15:32:38,855|INFO |MANAGER|com.neu.web.Rest$(sslContext:28): Import manager's certificate and private key to manager's keystore
2024-12-16 15:32:39,016|ERROR|MANAGER|org.apache.pekko.actor.OneForOneStrategy(applyOrElse$$anonfun$1:89): Could not initialize NSS
org.apache.pekko.actor.ActorInitializationException: pekko://manager-system/system/Materializers/StreamSupervisor-0/TLS-for-flow-1-1: exception during creation, root cause message: [configDir must be a directory: /etc/pki/nssdb]
	at org.apache.pekko.actor.ActorInitializationException$.apply(Actor.scala:206)
	at org.apache.pekko.actor.ActorCell.create(ActorCell.scala:679)
	at org.apache.pekko.actor.ActorCell.invokeAll$1(ActorCell.scala:523)
	at org.apache.pekko.actor.ActorCell.systemInvoke(ActorCell.scala:545)
	at org.apache.pekko.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:305)
	at org.apache.pekko.dispatch.Mailbox.run(Mailbox.scala:240)
	at org.apache.pekko.dispatch.Mailbox.exec(Mailbox.scala:253)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.security.ProviderException: Could not initialize NSS
	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:295)
	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11$1.run(SunPKCS11.java:179)
	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11$1.run(SunPKCS11.java:153)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11.configure(SunPKCS11.java:153)
	at java.base/sun.security.jca.ProviderConfig$3.run(ProviderConfig.java:257)
	at java.base/sun.security.jca.ProviderConfig$3.run(ProviderConfig.java:248)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.base/sun.security.jca.ProviderConfig.doLoadProvider(ProviderConfig.java:248)
	at java.base/sun.security.jca.ProviderConfig.getProvider(ProviderConfig.java:226)
	at java.base/sun.security.jca.ProviderList.getProvider(ProviderList.java:268)
	at java.base/sun.security.jca.ProviderList.getService(ProviderList.java:381)
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:157)
	at java.base/javax.net.ssl.SSLContext.getInstance(SSLContext.java:185)
	at com.neu.core.MySslConfiguration.sslContext(MySslConfiguration.scala:29)
	at com.neu.core.MySslConfiguration.sslContext$(MySslConfiguration.scala:23)
	at com.neu.web.Rest$.sslContext$lzyINIT1(Rest.scala:8)
	at com.neu.web.Rest$.sslContext(Rest.scala:8)
	at com.neu.core.BootedCore.com$neu$core$BootedCore$$https$$anonfun$1(Core.scala:42)
	at org.apache.pekko.http.scaladsl.ConnectionContext$.httpsServer$$anonfun$2(ConnectionContext.scala:54)
	at org.apache.pekko.http.scaladsl.HttpExt.sslTlsStage$$anonfun$1(Http.scala:855)
	at org.apache.pekko.stream.scaladsl.TLS$.apply$$anonfun$1(TLS.scala:208)
	at org.apache.pekko.stream.impl.io.TLSActor.liftedTree1$1(TLSActor.scala:174)
	at org.apache.pekko.stream.impl.io.TLSActor.<init>(TLSActor.scala:175)
	at org.apache.pekko.stream.impl.io.TLSActor$.props$$anonfun$1(TLSActor.scala:50)
	at org.apache.pekko.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:101)
	at org.apache.pekko.actor.Props.newActor(Props.scala:236)
	at org.apache.pekko.actor.ActorCell.newActor(ActorCell.scala:626)
	at org.apache.pekko.actor.ActorCell.create(ActorCell.scala:653)
	... 10 more
Caused by: java.io.IOException: configDir must be a directory: /etc/pki/nssdb
	at jdk.crypto.cryptoki/sun.security.pkcs11.Secmod.initialize(Secmod.java:218)
	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:290)
	... 38 more
	
```

IF I disable ssl using: 
manager.env.ssl=false

without ever hitting the UI I get 

```
2024-12-16 15:54:59,517|INFO |MANAGER|apache.pekko.event.slf4j.Slf4jLogger(applyOrElse:117): Slf4jLogger started
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.apache.pekko.http.scaladsl.HttpExt.sslTlsStage(Http.scala:858)
	at org.apache.pekko.http.scaladsl.HttpExt.sslTlsServerStage(Http.scala:845)
	at org.apache.pekko.http.scaladsl.HttpExt.fuseServerBidiFlow(Http.scala:114)
	at org.apache.pekko.http.scaladsl.HttpExt.bindAndHandle(Http.scala:253)
	at org.apache.pekko.http.scaladsl.HttpExt.bindAndHandleImpl(Http.scala:309)
	at org.apache.pekko.http.scaladsl.HttpExt.bindAndHandleAsync(Http.scala:374)
	at org.apache.pekko.http.scaladsl.HttpExt.bindAndHandleAsyncImpl(Http.scala:387)
	at org.apache.pekko.http.scaladsl.ServerBuilder$Impl.bind(ServerBuilder.scala:160)
	at com.neu.core.BootedCore.$init$(Core.scala:35)
	at com.neu.web.Rest$.<clinit>(Rest.scala:8)
	at com.neu.web.Rest.main(Rest.scala)
Caused by: java.security.ProviderException: Could not initialize NSS
	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:295)
	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11$1.run(SunPKCS11.java:179)
	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11$1.run(SunPKCS11.java:153)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11.configure(SunPKCS11.java:153)
	at java.base/sun.security.jca.ProviderConfig$3.run(ProviderConfig.java:257)
	at java.base/sun.security.jca.ProviderConfig$3.run(ProviderConfig.java:248)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.base/sun.security.jca.ProviderConfig.doLoadProvider(ProviderConfig.java:248)
	at java.base/sun.security.jca.ProviderConfig.getProvider(ProviderConfig.java:226)
	at java.base/sun.security.jca.ProviderList.getProvider(ProviderList.java:268)
	at java.base/sun.security.jca.ProviderList.getService(ProviderList.java:381)
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:157)
	at java.base/javax.net.ssl.SSLContext.getInstance(SSLContext.java:185)
	at java.base/javax.net.ssl.SSLContext.getDefault(SSLContext.java:110)
	at org.apache.pekko.stream.scaladsl.TLSPlacebo$.<clinit>(TLS.scala:232)
	... 11 more
Caused by: java.io.IOException: configDir must be a directory: /etc/pki/nssdb
	at jdk.crypto.cryptoki/sun.security.pkcs11.Secmod.initialize(Secmod.java:218)
	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:290)
	... 26 more
```

**Comment by xingzhang-suse** [comment]
Hi Seth,

Is this NeuVector cluster running in an environment with FIPS mode? We have a known issue in v5.4.0 and v5.4.1 which has the same error logs in manager pod.
If it it in FIPS as well, I would recommend to downgrade to v5.3.x and wait for our v5.4.2 release which will be in the end of December. We have fixed it and release it.

**Comment by Sbennett99** [comment]
That worked thank you
