### ISSUE TITLE
Network Activity not working for 5.1.x using Rancher Cluster Service

### ISSUE THREAD

**Issue by hwaastad** [neuvector/neuvector#647]
**Environment**
Platform: [e.g. Kubernetes, OpenShift, Rancher, Managed k8s (AKS, EKS, GKE, IKS, ...), ...]
Kubernetes/Platform Version(s): 
rancher 2.7.1, k8s 1.21->1.24

**Describe the bug**
A clear and concise description of what the bug is.  (If you are encountering a deployment error, check out the README or navigate to https://open-docs.neuvector.com for full deployment documentation.  Incorrect runtime is the most common reason for Controller and Enforcer CrashLoopBackOff events.)

Using cluster service to access Neuvector 5.1.0 or 5.1.1

**To Reproduce**
1. Install Neuvector with cluster tools chart, manager service NodePort
2. Click on Neuvector menu and go to Network Avtivity
3. The browser console will show:
`ERROR SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at a.loadBlacklist (2156.7fdd2d3c2a7acd5b.js:1:1228601)
    at a.ngOnInit (2156.7fdd2d3c2a7acd5b.js:1:1259906)
    at Dr (main.0ecb78f428b06699.js:1:7506885)
    at or (main.0ecb78f428b06699.js:1:7506707)
    at rs (main.0ecb78f428b06699.js:1:7506412)
    at Zc (main.0ecb78f428b06699.js:1:7534486)
    at Uf (main.0ecb78f428b06699.js:1:7534793)
    at Zc (main.0ecb78f428b06699.js:1:7534820)
    at uh (main.0ecb78f428b06699.js:1:7541881)`

4. Go to https://node:nodeport
5. Login with admin user
6. Go To Network Activity
7. Verify that graph is OK.

**Comment by hwaastad** [comment]
After more investigation, the reason is due to the change of formats on vars in localstorage (filters and blacklist) from 5.0 -> 5.1.
