### ISSUE TITLE
SSL Error - Java exception on RKE2 Helm chart install (Ironbank containers)

### ISSUE THREAD

**Issue by Morty800** [neuvector/neuvector#672]
**Environment**
Platform: [e.g. Kubernetes, OpenShift, Rancher, Managed k8s (AKS, EKS, GKE, IKS, ...), ...]
Kubernetes/Platform Version(s): Rancher RKE2 v1.25.6+rke2r1

**Describe the bug**
Web UI is inaccessible, container logs throw a java exception " java.lang.ClassCastException: class sun.security.pkcs11.P11Key$P11PrivateKey cannot be cast to class java.security.interfaces.RSAPrivateKey (sun.security.pkcs11.P11Key$P11PrivateKey is in module jdk.crypto.cryptoki of loader 'platform'; java.security.interfaces.RSAPrivateKey is in module java.base of loader 'bootstrap')"

**To Reproduce**

1. On a hardened (cis 1.23 profile) RKE2 cluster
2. `$ kubectl create namespace neuvector`
3. `$ kubectl label  namespace neuvector "pod-security.kubernetes.io/enforce=privileged"`
4. `$ kubectl create secret docker-registry regsecret -n neuvector --docker-server=https://your-private-registry/ --docker-username=your-name --docker-password=your-password --docker-email=your-email`
5. `$ helm install neuvector --namespace neuvector neuvector/core --set imagePullSecrets=regsecret,registry=your-private-registry,k3s.enabled=true` (private registry is Ironbank in this case)

**Expected behavior**
Initial neuvector is installed with access to the webUI utilizing default self-signed certificates

**Actual behavior**

1. All pods show as "Running"
2. `k logs manager-pod-name -n neuvector`

```
2023-02-22 22:16:35,911|INFO |MANAGER|com.neu.web.Rest$(sslContext:31): Import manager's certificate and private key to manager's keystore
2023-02-22 22:16:35,921|INFO |MANAGER|com.neu.web.Rest$(sslContext:53): PKCS#8 private key is being used
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.neu.web.Rest.main(Rest.scala)
Caused by: java.lang.ClassCastException: class sun.security.pkcs11.P11Key$P11PrivateKey cannot be cast to class java.security.interfaces.RSAPrivateKey (sun.security.pkcs11.P11Key$P11PrivateKey is in module jdk.crypto.cryptoki of loader 'platform'; java.security.interfaces.RSAPrivateKey is in module java.base of loader 'bootstrap')
        at com.neu.core.MySslConfiguration$class.sslContext(MySslConfiguration.scala:62)
        at com.neu.web.Rest$.sslContext(Rest.scala:6)
        at com.neu.core.MySslConfiguration$class.$init$(MySslConfiguration.scala:153)
        at com.neu.web.Rest$.<init>(Rest.scala:6)
        at com.neu.web.Rest$.<clinit>(Rest.scala)
        ... 1 more
```

3. Web UI is unavailable

**Additional context**
Also tried replacing certificates following [this documentation](open-docs.neuvector.com/configuration/console/replacecert)

When using the PKCS#1 certificate it errors as it only wants PKCS#8, when using PKCS#8 certificates it gives the same error above.

**Comment by Morty800** [comment]
Issue will be addressed in the Ironbank gitlab
